services:
  web:
    build: .
    container_name: fastapi_app
    env_file: .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: postgres_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
